# Generated by Django 3.2 on 2021-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='isbn_number',
            field=models.CharField(default=7432439370, max_length=10, unique=True),
        ),
    ]
